name: publish-site
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: 'git config user.name github-actions[bot]

          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          '
      - id: measurement-3
        name: Record Measurement After Configure Git Credentials
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Configure Git Credentials
          task: get-measurement
      - uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: docs/requirements.txt
          python-version: 3.11
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: 'mkdocs-material-

            '
      - run: pip install -r docs/requirements.txt
      - id: measurement-7
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Step
          task: get-measurement
      - name: Deploy
        run: mkdocs gh-deploy --force
        working-directory: docs
      - id: measurement-9
        name: Record Measurement After Deploy
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Deploy
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
permissions:
  contents: write
