name: Check docs
on:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: '0'
  RUSTFLAGS: -C debuginfo=0
jobs:
  check-docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: docs/requirements.txt
          python-version: 3.11
      - run: pip install -r docs/requirements.txt
      - id: measurement-4
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Step
          task: get-measurement
      - name: Check links
        run: 'mkdocs-linkcheck src

          '
        working-directory: docs
      - id: measurement-6
        name: Record Measurement After Check links
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check links
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
