name: Check license headers
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install license-header-checker
        run: curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh
          | bash
      - id: measurement-3
        name: Record Measurement After Install license-header-checker
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install license-header-checker
          task: get-measurement
      - name: Check license headers (rust)
        run: ./bin/license-header-checker -a -v ./rust/license_header.txt rust rs
          && [[ -z `git status -s` ]]
      - id: measurement-5
        name: Record Measurement After Check license headers (rust)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check license headers (rust)
          task: get-measurement
      - name: Check license headers (python)
        run: ./bin/license-header-checker -a -v ./python/license_header.txt python
          py && [[ -z `git status -s` ]]
      - id: measurement-7
        name: Record Measurement After Check license headers (python)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check license headers (python)
          task: get-measurement
      - name: Check license headers (protos)
        run: ./bin/license-header-checker -a -v ./protos/license_header.txt protos
          proto && [[ -z `git status -s` ]]
      - id: measurement-9
        name: Record Measurement After Check license headers (protos)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check license headers (protos)
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
