name: Nightly Run Jobs
on:
  push:
    branches:
      - main

jobs:
  run:
    if: github.repository == 'lancedb/lance'
    runs-on: ubuntu-24.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Nightly Run File Verification Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: file_verification.yml
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
